<section class="mx-auto w-full max-w-7xl space-y-6">
    <header class="flex flex-wrap items-start justify-between gap-4"><div><flux:heading size="xl" level="1">{{ $owner ? 'Staf dan mekanik' : 'Mekanik' }}</flux:heading><flux:text class="mt-1">{{ $owner ? 'Kelola akun staf, peran, dan akses bengkel.' : 'Mekanik aktif dan jumlah servis yang belum diserahkan.' }}</flux:text></div>@if ($owner)<flux:button variant="primary" icon="plus" wire:click="create" x-on:staff-editor-closed.window="if ($event.detail.id === null) $nextTick(() => $el.focus())">Tambah staf</flux:button>@endif</header>
    @if (session('status'))<p role="status" class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800 dark:border-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">{{ session('status') }}</p>@endif
    @if ($errors->any())<div role="alert" class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-800 dark:bg-red-950 dark:text-red-200"><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @if ($owner)<livewire:staff-editor />@endif
    <div class="flex flex-wrap items-end justify-between gap-4"><div class="w-full sm:max-w-md"><flux:input wire:model.live.debounce.300ms="search" label="Cari nama staf" type="search" maxlength="120" icon="magnifying-glass" /></div><p role="status" class="text-sm text-zinc-500">{{ $staff->total() }} staf <span wire:loading wire:target="search">· Mencari…</span></p></div>
    <div class="overflow-x-auto rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900"><table class="workshop-responsive-table w-full text-left text-sm" role="table"><caption class="sr-only">Daftar staf aktif</caption><thead role="rowgroup" class="border-b border-zinc-200 bg-zinc-50 text-zinc-600 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-300"><tr role="row"><th role="columnheader" scope="col" class="px-5 py-3">Nama</th><th role="columnheader" scope="col" class="px-5 py-3">Peran</th><th role="columnheader" scope="col" class="px-5 py-3">Servis aktif</th>@if ($owner)<th role="columnheader" scope="col" class="px-5 py-3 text-right">Tindakan</th>@endif</tr></thead><tbody role="rowgroup" class="divide-y divide-zinc-100 dark:divide-zinc-800">
    @forelse ($staff as $person)<tr role="row" wire:key="staff-{{ $person->id }}"><td role="cell" data-label="Nama" class="px-5 py-4"><p class="font-medium">{{ $person->name }}</p>@if ($owner)<p class="mt-1 text-zinc-500">{{ $person->email }}</p>@endif</td><td role="cell" data-label="Peran" class="px-5 py-4">{{ $person->role->label() }}</td><td role="cell" data-label="Servis aktif" class="px-5 py-4 tabular-nums">{{ $person->active_orders }}</td>@if ($owner)<td role="cell" data-label="Tindakan" class="px-5 py-4 text-right"><flux:button size="sm" variant="ghost" wire:click="edit({{ $person->id }})" x-on:staff-editor-closed.window="if ($event.detail.id === {{ $person->id }}) $nextTick(() => $el.focus())" aria-label="Edit {{ $person->name }}">Edit</flux:button><flux:button size="sm" variant="ghost" wire:click="deactivate({{ $person->id }})" wire:confirm="Nonaktifkan staf ini? Akses masuk dihentikan, riwayat tetap tersimpan. Pemulihan belum tersedia di halaman ini." wire:loading.attr="disabled" aria-label="Nonaktifkan {{ $person->name }}">Nonaktifkan</flux:button></td>@endif</tr>
    @empty<tr role="row"><td role="cell" colspan="{{ $owner ? 4 : 3 }}" class="px-5 py-12 text-center text-zinc-500">Tidak ada staf yang cocok.</td></tr>@endforelse
    </tbody></table></div>{{ $staff->links() }}
</section>
