<section class="mx-auto w-full max-w-7xl space-y-6">
    <header class="flex flex-wrap items-start justify-between gap-4">
        <div><flux:heading size="xl" level="1">Bon & penjualan</flux:heading><flux:text class="mt-1">Draf, transaksi terkunci, pembayaran, dan koreksi pembukuan.</flux:text></div>
        <flux:button variant="primary" icon="plus" href="{{ route('receipts.create') }}" wire:navigate>Penjualan baru</flux:button>
    </header>
    @if(session('status'))<p role="status" class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">{{ session('status') }}</p>@endif
    @if($errors->any())<div role="alert" class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:bg-red-950 dark:text-red-200"><ul class="list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="grid items-end gap-4 md:grid-cols-4"><flux:input wire:model.live.debounce.300ms="search" label="Cari bon / pelanggan" type="search" maxlength="120"/><flux:select wire:model.live="status" label="Status bon"><option value="">Semua</option>@foreach(\App\Enums\ReceiptStatus::cases() as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</flux:select><flux:select wire:model.live="paymentStatus" label="Status bayar"><option value="">Semua</option>@foreach(\App\Enums\PaymentStatus::cases() as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</flux:select><flux:input wire:model.live="date" label="Tanggal transaksi" type="date"/></div>
    <p role="status" class="text-sm text-zinc-500">{{ $receipts->total() }} bon <span wire:loading>· Memuat…</span></p>
    <div class="overflow-x-auto rounded-xl border border-zinc-200 dark:border-zinc-700"><table class="workshop-responsive-table w-full text-left text-sm" role="table"><caption class="sr-only">Daftar bon</caption><thead role="rowgroup" class="bg-zinc-50 dark:bg-zinc-800"><tr role="row"><th role="columnheader" class="p-4">Bon / tanggal</th><th role="columnheader" class="p-4">Pelanggan / motor</th><th role="columnheader" class="p-4">Status</th><th role="columnheader" class="p-4 text-right">Total (Rp)</th><th role="columnheader" class="p-4 text-right">Tindakan</th></tr></thead><tbody role="rowgroup" class="divide-y divide-zinc-100 dark:divide-zinc-800">@forelse($receipts as $receipt)<tr role="row" wire:key="receipt-{{ $receipt->id }}"><td role="cell" data-label="Bon / tanggal" class="p-4 font-medium">{{ $receipt->receipt_number }}<p class="text-xs text-zinc-500">{{ $receipt->transaction_date->format('d/m/Y H:i') }}</p></td><td role="cell" data-label="Pelanggan / motor" class="p-4">{{ $receipt->customer_snapshot['name'] ?? $receipt->customer?->name ?? 'Umum' }}<p class="text-xs text-zinc-500">{{ $receipt->vehicle_snapshot['license_plate'] ?? $receipt->vehicle?->license_plate }}</p></td><td role="cell" data-label="Status" class="p-4">{{ $receipt->status->label() }} · {{ $receipt->payment_status->label() }}</td><td role="cell" data-label="Total (Rp)" class="p-4 text-right tabular-nums">{{ $receipt->grand_total }}</td><td role="cell" data-label="Tindakan" class="p-4 text-right"><flux:button size="sm" href="{{ route('receipts.edit', $receipt) }}" wire:navigate>Detail</flux:button></td></tr>@empty<tr role="row"><td role="cell" colspan="5" class="p-10 text-center text-zinc-500">Tidak ada bon yang cocok. Buat penjualan baru atau bon dari servis selesai.</td></tr>@endforelse</tbody></table></div>
    {{ $receipts->links() }}
</section>
